version: '3.8'

services:
  db:
    image: postgres:16.3
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    network_mode: host
  adminer:
    image: adminer:latest
    # ports:
      # - 7070:8080
    network_mode: host
